from __future__ import annotations

import isaaclab.sim as sim_utils
from isaaclab.assets import DeformableObjectCfg

# NOTE: parameters generated by chatgpt
BALL_CFG = DeformableObjectCfg(
    prim_path="{ENV_REGEX_NS}/Ball",
    spawn=sim_utils.MeshSphereCfg(
        radius=0.11,
        deformable_props=sim_utils.DeformableBodyPropertiesCfg(
            deformable_enabled=True,
            self_collision=True,
            # tighter but safe contact for crisp grabbing / bounce
            contact_offset=0.005,  # try 0.004-0.008
            rest_offset=0.0,
            # solver iterations: higher -> more stable contact / FEM convergence
            solver_position_iteration_count=120,  # 100-150 is a good stable range
            # small nodal damping so ball keeps lively response but doesn't oscillate
            vertex_velocity_damping=0.0008,  # 5e-4 .. 2e-3
            # FEM resolution: keep high if you want realistic deformation detail
            simulation_hexahedral_resolution=48,
        ),
        physics_material=sim_utils.DeformableBodyMaterialCfg(
            # mass = 0.43 kg -> density = 0.43 / (4/3*pi*0.11^3) ≈ 77.13
            density=77.13,
            # stiff-but-slightly-compressible to mimic inflated shell when using full-volume
            youngs_modulus=3.0e7,  # start here; tune 1e7 - 5e7
            poissons_ratio=0.48,  # near-incompressible but numerically stable
            # squashiness / energy loss
            elasticity_damping=0.0015,
            damping_scale=0.4,
            # surface interaction (adjust for grass/boot)
            dynamic_friction=0.25,
        ),
        visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(1.0, 1.0, 1.0)),
    ),
    init_state=DeformableObjectCfg.InitialStateCfg(pos=(14.0, -16.0, 5.0)),
    debug_vis=False,
)
