[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.10.22"

# Description
title = "Booster IsaacLab Tasks"
description="Extension containing suite of environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning", "booster"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}

[[python.module]]
name = "booster_tasks"
