name: Python Formatter & Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # adjust to your env

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      # Step 4: Run Black (check mode)
      - name: Check Python formatting with Black
        run: black --check .

      # Step 5: Run Ruff linter
      - name: Lint Python with Ruff
        run: ruff check .
